Flownative:
  Google:
    CloudStorage:
      profiles:
        # Default credentials and client options - override these in your settings with real values
        default:
          credentials:
            clientEmail: '123456789012-abc123defg456hijklmnopqrstuvwxyz@developer.gserviceaccount.com'
            privateKeyP12PathAndFilename: 'Data/Secrets/MyGoogleProject-abc123457def.p12'
